# Generated by Django 3.2 on 2023-08-16 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha Tutoria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tema Tratado')),
                ('teacher', models.OneToOneField(limit_choices_to={'groups__name': 'profesores'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Tutoria',
                'verbose_name_plural': 'Tutorias',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Alumno Regular')),
                ('time_quantity', models.PositiveIntegerField(default=0, verbose_name='Tiempo Empleado')),
                ('modalidad', models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual')], default='P', max_length=1, verbose_name='Modalidad')),
                ('firma', models.ImageField(blank=True, default='default.png', null=True, upload_to='firmas/')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'estudiantes'}, on_delete=django.db.models.deletion.CASCADE, related_name='students_registration', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('tuto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutoria', verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_1', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Nota 1')),
                ('mark_2', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Nota 2')),
                ('mark_3', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Nota 3')),
                ('average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Promedio')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'estudiantes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('tuto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutoria', verbose_name='Tutoria')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(blank=True, default=False, null=True, verbose_name='Presente')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'estudiantes'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('tuto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutoria', verbose_name='Tutoria')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
