# Generated by Django 3.2 on 2023-08-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark_1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Nota 1'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Nota 2'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Nota 3'),
        ),
    ]
