# Generated by Django 3.2 on 2023-08-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230816_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Promedio'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Nota 1'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Nota 2'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Nota 3'),
        ),
    ]
