# Generated by Django 3.2 on 2023-08-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230816_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoria',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pending', max_length=10),
        ),
    ]
