# Generated by Django 4.2.4 on 2023-08-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(default='users/default.png', upload_to='users/', verbose_name='Imagen de perfil'),
        ),
    ]
